# Generated by Django 3.0.3 on 2020-03-04 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0002_mocktest_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='likes',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='registerations',
            field=models.ManyToManyField(blank=True, null=True, related_name='registerations', to=settings.AUTH_USER_MODEL),
        ),
    ]
