# Generated by Django 3.0.3 on 2020-03-14 10:11

import ckeditor_uploader.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200314_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='section1',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2020, 3, 14, 10, 11, 20, 512108, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listening',
            name='section2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2020, 3, 14, 10, 11, 30, 22477, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listening',
            name='section3',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='listening',
            name='section4',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='passage1',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='passage2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='passage3',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='speaking',
            name='part1',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='speaking',
            name='part2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='speaking',
            name='part3',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='writing',
            name='task1',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='writing',
            name='task2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
