# Generated by Django 3.0.3 on 2020-04-25 16:54

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [41.3, 69.26667], 'marker_color': 'blue'}, null=True),
        ),
    ]
