from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()
from teacher.models import MockTest

def upload_location(instance, filename):
    return '%s/%s'%(instance.id, filename)

class AnswerWritingStudent(models.Model):
    mocktest = models.ForeignKey(MockTest, on_delete = models.CASCADE)
    student = models.ForeignKey(User, on_delete = models.CASCADE)
    task1 = models.TextField(null=True, blank=True)
    task2 = models.TextField(null=True, blank=True)
    pdf = models.FileField(upload_to=upload_location, null=True, blank=True)
    create_time = models.DateField(auto_now_add=True)
    is_checked = models.BooleanField(default=False)

class AnswerSpeakingStudent(models.Model):
    mocktest = models.ForeignKey(MockTest, on_delete = models.CASCADE)
    student = models.ForeignKey(User, on_delete = models.CASCADE)
    audio = models.FileField(upload_to=upload_location, null=True, blank=True)
    create_time = models.DateField(auto_now_add=True)
    is_checked = models.BooleanField(default=False)

class AnswerReadingStudent(models.Model):
    mocktest = models.ForeignKey(MockTest, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    a1 = models.CharField(max_length=100, null=True, blank=True)
    a2 = models.CharField(max_length=100, null=True, blank=True)
    a3 = models.CharField(max_length=100, null=True, blank=True)
    a4 = models.CharField(max_length=100, null=True, blank=True)
    a5 = models.CharField(max_length=100, null=True, blank=True)
    a6 = models.CharField(max_length=100, null=True, blank=True)
    a7 = models.CharField(max_length=100, null=True, blank=True)
    a8 = models.CharField(max_length=100, null=True, blank=True)
    a9 = models.CharField(max_length=100, null=True, blank=True)
    a10 = models.CharField(max_length=100, null=True, blank=True)
    a11 = models.CharField(max_length=100, null=True, blank=True)
    a12 = models.CharField(max_length=100, null=True, blank=True)
    a13 = models.CharField(max_length=100, null=True, blank=True)
    a14 = models.CharField(max_length=100, null=True, blank=True)
    a15 = models.CharField(max_length=100, null=True, blank=True)
    a16 = models.CharField(max_length=100, null=True, blank=True)
    a17 = models.CharField(max_length=100, null=True, blank=True)
    a18 = models.CharField(max_length=100, null=True, blank=True)
    a19 = models.CharField(max_length=100, null=True, blank=True)
    a20 = models.CharField(max_length=100, null=True, blank=True)
    a21 = models.CharField(max_length=100, null=True, blank=True)
    a22 = models.CharField(max_length=100, null=True, blank=True)
    a23 = models.CharField(max_length=100, null=True, blank=True)
    a24 = models.CharField(max_length=100, null=True, blank=True)
    a25 = models.CharField(max_length=100, null=True, blank=True)
    a26 = models.CharField(max_length=100, null=True, blank=True)
    a27 = models.CharField(max_length=100, null=True, blank=True)
    a28 = models.CharField(max_length=100, null=True, blank=True)
    a29 = models.CharField(max_length=100, null=True, blank=True)
    a30 = models.CharField(max_length=100, null=True, blank=True)
    a31 = models.CharField(max_length=100, null=True, blank=True)
    a32 = models.CharField(max_length=100, null=True, blank=True)
    a33 = models.CharField(max_length=100, null=True, blank=True)
    a34 = models.CharField(max_length=100, null=True, blank=True)
    a35 = models.CharField(max_length=100, null=True, blank=True)
    a36 = models.CharField(max_length=100, null=True, blank=True)
    a37 = models.CharField(max_length=100, null=True, blank=True)
    a38 = models.CharField(max_length=100, null=True, blank=True)
    a39 = models.CharField(max_length=100, null=True, blank=True)
    a40 = models.CharField(max_length=100, null=True, blank=True)

class AnswerListeningStudent(models.Model):
    mocktest = models.ForeignKey(MockTest, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    a1 = models.CharField(max_length=100, null=True, blank=True)
    a2 = models.CharField(max_length=100, null=True, blank=True)
    a3 = models.CharField(max_length=100, null=True, blank=True)
    a4 = models.CharField(max_length=100, null=True, blank=True)
    a5 = models.CharField(max_length=100, null=True, blank=True)
    a6 = models.CharField(max_length=100, null=True, blank=True)
    a7 = models.CharField(max_length=100, null=True, blank=True)
    a8 = models.CharField(max_length=100, null=True, blank=True)
    a9 = models.CharField(max_length=100, null=True, blank=True)
    a10 = models.CharField(max_length=100, null=True, blank=True)
    a11 = models.CharField(max_length=100, null=True, blank=True)
    a12 = models.CharField(max_length=100, null=True, blank=True)
    a13 = models.CharField(max_length=100, null=True, blank=True)
    a14 = models.CharField(max_length=100, null=True, blank=True)
    a15 = models.CharField(max_length=100, null=True, blank=True)
    a16 = models.CharField(max_length=100, null=True, blank=True)
    a17 = models.CharField(max_length=100, null=True, blank=True)
    a18 = models.CharField(max_length=100, null=True, blank=True)
    a19 = models.CharField(max_length=100, null=True, blank=True)
    a20 = models.CharField(max_length=100, null=True, blank=True)
    a21 = models.CharField(max_length=100, null=True, blank=True)
    a22 = models.CharField(max_length=100, null=True, blank=True)
    a23 = models.CharField(max_length=100, null=True, blank=True)
    a24 = models.CharField(max_length=100, null=True, blank=True)
    a25 = models.CharField(max_length=100, null=True, blank=True)
    a26 = models.CharField(max_length=100, null=True, blank=True)
    a27 = models.CharField(max_length=100, null=True, blank=True)
    a28 = models.CharField(max_length=100, null=True, blank=True)
    a29 = models.CharField(max_length=100, null=True, blank=True)
    a30 = models.CharField(max_length=100, null=True, blank=True)
    a31 = models.CharField(max_length=100, null=True, blank=True)
    a32 = models.CharField(max_length=100, null=True, blank=True)
    a33 = models.CharField(max_length=100, null=True, blank=True)
    a34 = models.CharField(max_length=100, null=True, blank=True)
    a35 = models.CharField(max_length=100, null=True, blank=True)
    a36 = models.CharField(max_length=100, null=True, blank=True)
    a37 = models.CharField(max_length=100, null=True, blank=True)
    a38 = models.CharField(max_length=100, null=True, blank=True)
    a39 = models.CharField(max_length=100, null=True, blank=True)
    a40 = models.CharField(max_length=100, null=True, blank=True)