# Generated by Django 3.0.3 on 2020-03-10 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_auto_20200304_1837'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerReadingStudent',
            new_name='AnszwerReadingStudent',
        ),
    ]
