# Generated by Django 3.0.3 on 2020-03-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200311_0218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnszwerReadingStudent',
        ),
    ]
