# Generated by Django 3.0.3 on 2020-03-10 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_auto_20200304_1837'),
        ('student', '0003_delete_anszwerreadingstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReadingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.CharField(blank=True, max_length=100, null=True)),
                ('a2', models.CharField(blank=True, max_length=100, null=True)),
                ('a3', models.CharField(blank=True, max_length=100, null=True)),
                ('a4', models.CharField(blank=True, max_length=100, null=True)),
                ('a5', models.CharField(blank=True, max_length=100, null=True)),
                ('a6', models.CharField(blank=True, max_length=100, null=True)),
                ('a7', models.CharField(blank=True, max_length=100, null=True)),
                ('a8', models.CharField(blank=True, max_length=100, null=True)),
                ('a9', models.CharField(blank=True, max_length=100, null=True)),
                ('a10', models.CharField(blank=True, max_length=100, null=True)),
                ('a11', models.CharField(blank=True, max_length=100, null=True)),
                ('a12', models.CharField(blank=True, max_length=100, null=True)),
                ('a13', models.CharField(blank=True, max_length=100, null=True)),
                ('a14', models.CharField(blank=True, max_length=100, null=True)),
                ('a15', models.CharField(blank=True, max_length=100, null=True)),
                ('a16', models.CharField(blank=True, max_length=100, null=True)),
                ('a17', models.CharField(blank=True, max_length=100, null=True)),
                ('a18', models.CharField(blank=True, max_length=100, null=True)),
                ('a19', models.CharField(blank=True, max_length=100, null=True)),
                ('a20', models.CharField(blank=True, max_length=100, null=True)),
                ('a21', models.CharField(blank=True, max_length=100, null=True)),
                ('a22', models.CharField(blank=True, max_length=100, null=True)),
                ('a23', models.CharField(blank=True, max_length=100, null=True)),
                ('a24', models.CharField(blank=True, max_length=100, null=True)),
                ('a25', models.CharField(blank=True, max_length=100, null=True)),
                ('a26', models.CharField(blank=True, max_length=100, null=True)),
                ('a27', models.CharField(blank=True, max_length=100, null=True)),
                ('a28', models.CharField(blank=True, max_length=100, null=True)),
                ('a29', models.CharField(blank=True, max_length=100, null=True)),
                ('a30', models.CharField(blank=True, max_length=100, null=True)),
                ('a31', models.CharField(blank=True, max_length=100, null=True)),
                ('a32', models.CharField(blank=True, max_length=100, null=True)),
                ('a33', models.CharField(blank=True, max_length=100, null=True)),
                ('a34', models.CharField(blank=True, max_length=100, null=True)),
                ('a35', models.CharField(blank=True, max_length=100, null=True)),
                ('a36', models.CharField(blank=True, max_length=100, null=True)),
                ('a37', models.CharField(blank=True, max_length=100, null=True)),
                ('a38', models.CharField(blank=True, max_length=100, null=True)),
                ('a39', models.CharField(blank=True, max_length=100, null=True)),
                ('a40', models.CharField(blank=True, max_length=100, null=True)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.MockTest')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
