# Generated by Django 3.0.3 on 2020-03-13 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_answerreadingstudent_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlisteningstudent',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 3, 13, 5, 52, 10, 762566, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
