# Generated by Django 3.0.3 on 2020-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_answerlisteningstudent_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlisteningstudent',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerreadingstudent',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
