# Generated by Django 3.0.3 on 2020-03-13 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_auto_20200304_1837'),
        ('student', '0011_auto_20200313_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerWritingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pdf', models.FileField(upload_to=student.models.upload_location)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.MockTest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSpeakingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=student.models.upload_location)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.MockTest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
