# Generated by Django 3.0.3 on 2020-03-13 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_answerspeakingstudent_answerwritingstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerspeakingstudent',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 3, 13, 15, 57, 59, 969904, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerspeakingstudent',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerwritingstudent',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 3, 13, 15, 58, 15, 318821, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerwritingstudent',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
