# Generated by Django 3.0.3 on 2020-03-13 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200313_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerwritingstudent',
            old_name='content',
            new_name='task1',
        ),
        migrations.AddField(
            model_name='answerwritingstudent',
            name='task2',
            field=models.TextField(default=datetime.datetime(2020, 3, 13, 16, 17, 12, 772642, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
