# Generated by Django 3.0.3 on 2020-03-14 05:39

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200313_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerspeakingstudent',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_location),
        ),
        migrations.AlterField(
            model_name='answerwritingstudent',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_location),
        ),
        migrations.AlterField(
            model_name='answerwritingstudent',
            name='task1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerwritingstudent',
            name='task2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
