# Generated by Django 3.0.3 on 2020-03-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200314_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlisteningstudent',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='answerlisteningstudent',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='answerreadingstudent',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='answerreadingstudent',
            name='is_checked',
        ),
    ]
